### ISSUE TITLE
Creating the Spa 

### ISSUE THREAD

**Issue by DrFacepalm** [MatrixAI/Typescript-Demo-Spa#2]
We need an example of a single page application, using vue. Polykey is already using vue, so it's a matter of using the vue infrastructure in polykey with the boilerplate in Typescript-Demo-Lib. 

Relates to #1. 

Resources: 
https://blog.logrocket.com/how-to-write-a-vue-js-app-completely-in-typescript/

**Comment by CMCDragonkai** [comment]
Done in #3.
