### ISSUE TITLE
Storybook Integration

### ISSUE THREAD

**Issue by DrFacepalm** [MatrixAI/Typescript-Demo-Spa#4]
I've looked into storybook but for vue3, it seems like the support is still being developed.

storybookjs/storybook#10654
This issue goes into the progress of that.

There is a work in progress package released here: https://www.npmjs.com/package/@andoshin11/storybook-vue3 though.

**Comment by CMCDragonkai** [comment]
Storybook isn't compatible yet, so we will leave it out.
