### ISSUE TITLE
Testing issues

### ISSUE THREAD

**Issue by DrFacepalm** [MatrixAI/Typescript-Demo-Spa#5]
As of right now, the setup works when testing the app component, but if the `App` component has an `<img src="...">` in it, an error is thrown:

![image](https://user-images.githubusercontent.com/31267481/94432381-0860ec00-01da-11eb-90ee-52dc41f2228e.png)

**Comment by CMCDragonkai** [comment]
The syntax error says its an invalid token. That's pretty strange. Are you closing or missing some `/>` somewhere?

**Comment by CMCDragonkai** [comment]
All tests are working now with #11.
